language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.5
      env: dependencies=lowest
    - php: 5.6
      env: dependencies=lowest
    - php: 7
      env: dependencies=lowest

before_script:
  - travis_retry composer self-update
  - if [ -z "$dependencies" ]; then travis_retry composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then travis_retry composer update --prefer-lowest -n; fi;

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/clover.xml; fi